export const generationTypes: GenerationType[] = [
    /*{
        name: 'Info General',
        courseCodes: [
            'I01',
            'I02',
            'I03',
            'I04',
            'I05',
            'I06',
            'I07',
            'I08',
            'I09',
            'I10',
            'I11',
            'I12',
            'I13',
            'I14',
            'I15',
            'I16',
            'I17',
            'I18',
            'I19',
        ],
        major: 'Infó',
        imsc: false,
        german: false,
        groupCount: 19,
        allowMultipleGirlRooms: false,
    },
    {
        name: 'Info IMSC',
        courseCodes: ['I_IMSc1', 'I_IMSc2', 'I_IMSc3'],
        major: 'Infó',
        imsc: true,
        german: false,
        groupCount: 3,
        allowMultipleGirlRooms: true,
    },
    {
        name: 'Info German',
        courseCodes: ['I_NÉMET'],
        major: 'Infó',
        imsc: false,
        german: true,
        groupCount: 1,
        allowMultipleGirlRooms: false,
    },*/
    {
        name: 'Vill General',
        courseCodes: ['V01', 'V02', 'V03', 'V04', 'V05', 'V06', 'V07', 'V08'],
        major: 'Vill',
        imsc: false,
        german: false,
        groupCount: 8,
        allowMultipleGirlRooms: true,
    },
    /*{
        name: 'Vill IMSC',
        courseCodes: ['V_IMSc1', 'V_IMSc2'],
        major: 'Vill',
        imsc: true,
        german: false,
        groupCount: 2,
        allowMultipleGirlRooms: false,
    },
    {
        name: 'Vill German',
        courseCodes: ['V_NÉMET'],
        major: 'Vill',
        imsc: false,
        german: true,
        groupCount: 1,
        allowMultipleGirlRooms: false,
    },
    {
        name: 'Bprof General',
        courseCodes: ['BPI01', 'BPI02', 'BPI03'],
        major: 'Üzinfó',
        imsc: false,
        german: false,
        groupCount: 3,
        allowMultipleGirlRooms: true,
    },*/
];
